= ProjekthandAuto
Jonas, David, Philipp, Julius
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlight.js
:icons: font

IMPORTANT: Copyright (C) 2020 - present Jonas, David, Philipp, Julius, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Ein kurzer Überblick über die Architektur und Hauptfunktionen des Applikationsservers.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.plantuml[]
----

Beschreibung der wichtigsten Anwendungsfälle und Systemprozesse.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.plantuml[]
----

Darstellung der wichtigsten Softwarekomponenten und ihrer Beziehungen.

=== Die REST-Schnittstelle

Übersicht über die bereitgestellten REST-Endpunkte des Systems.

."AutoGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,AutoGetController,svg]
----
include::AutoGetController.plantuml[]
----

Beschreibung der Controller für Leseoperationen.

."Sequenzdiagramm" mit den Methodenaufrufen
[plantuml,sequenzdiagramm,svg]
----
include::sequenzdiagramm.plantuml[]
----

Darstellung der Abläufe und Aufrufe zwischen den Komponenten.

."AutoWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,AutoWriteController,svg]
----
include::AutoWriteController.plantuml[]
----

Beschreibung der Controller für Schreiboperationen.

=== Die GraphQL-Schnittstelle

Überblick über die Funktionen und Möglichkeiten der GraphQL-Schnittstelle.

.AutoQueryResolver für Lesezugriffe an der GraphQL-Schnittstelle
[plantuml,AutoQueryResolver,svg]
----
include::AutoQueryResolver.plantuml[]
----

GraphQL-Resolver für Leseoperationen.

.AutoMutationResolver für Schreibzugriffe an der GraphQL-Schnittstelle
[plantuml,AutoMutationResolver,svg]
----
include::AutoMutationResolver.plantuml[]
----

GraphQL-Resolver für Schreiboperationen.

=== Die Geschäftslogik

Beschreibung der Geschäftslogik und der wichtigsten Services.

."AutoReadService" von der Geschäftslogik
[plantuml,AutoReadService,svg]
----
include::AutoReadService.plantuml[]
----

Service für Lesevorgänge innerhalb der Geschäftslogik.

."AutoWriteService" von der Geschäftslogik
[plantuml,AutoWriteService,svg]
----
include::AutoWriteService.plantuml[]
----

Service für Schreibvorgänge innerhalb der Geschäftslogik.

=== Klasse für Entities

Beschreibung der verwendeten Entity-Klassen und deren Struktur.

.Entity
[plantuml,Auto,svg]
----
include::Auto.plantuml[]
----

Darstellung der Auto-Entity mit Attributen und Beziehungen.

=== ER-Diagramm

Visuelle Darstellung der Datenbankstruktur und der Beziehungen zwischen den Entitäten.

.ER-Diagramm
[plantuml,ER-Diagramm,svg]
----
include::ER-Diagramm.plantuml[]
----
